[package]
name = "parse-changelog"
version = "0.2.2"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/parse-changelog"
documentation = "https://docs.rs/parse-changelog"
keywords = ["changelog", "parser"]
categories = ["command-line-utilities", "parsing", "text-processing"]
exclude = ["/.*", "/scripts"]
description = """
A simple changelog parser, written in Rust.
"""

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[workspace]

[[bin]]
name = "parse-changelog"
required-features = ["default"]

[features]
# When using this crate as a library, disable default features.
default = ["anyhow", "structopt", "regex/perf"]

# NB: indexmap and regex are public dependencies.
[dependencies]
indexmap = { version = "1.5.2", features = ["std"] }
once_cell = "1"
regex = { version = "1.3", default-features = false, features = ["std", "unicode"] }

anyhow = { version = "1.0.20", optional = true }
structopt = { version = "0.3", optional = true }

[dev-dependencies]
easy-ext = "0.2"
tempfile = "3"
rustversion = "1"
