[package]
name = "parse-changelog"
version = "0.4.4"
authors = ["Taiki Endo <te316e89@gmail.com>"]
edition = "2018"
rust-version = "1.54"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/parse-changelog"
keywords = ["changelog", "parser"]
categories = ["command-line-utilities", "parser-implementations", "text-processing"]
exclude = ["/.*", "/tools"]
description = """
Simple changelog parser, written in Rust.
"""

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
resolver = "2"
members = ["bench", "tools/codegen"]

[[bin]]
name = "parse-changelog"
required-features = ["default"]

[features]
# When using this crate as a library, we recommend disabling the default features.
default = ["anyhow", "clap", "clap_derive", "serde", "serde_json"]
# Implements serde::Serialize trait for parse-changelog types.
serde = ["serde-crate", "indexmap/serde-1"]

# Note: indexmap and serde are public dependencies.
[dependencies]
indexmap = { version = "1.5.2", features = ["std"] }
memchr = "2.4"
once_cell = "1"
regex = "1"

anyhow = { version = "1.0.34", optional = true }
clap = { version = "=3.0.0-beta.4", optional = true, default-features = false, features = ["cargo", "derive", "std", "suggestions"] }
serde-crate = { package = "serde", version = "1.0.103", optional = true, features = ["derive"] }
serde_json = { version = "1", optional = true }

# This is needed until https://github.com/clap-rs/clap/pull/2706 is released.
clap_derive = { version = "=3.0.0-beta.4", optional = true }

[dev-dependencies]
easy-ext = "1"
tempfile = "3"
