[package]
name = "bench"
version = "0.0.0"
edition = "2018"
publish = false

[dev-dependencies]
parse-changelog = { path = "..", default-features = false }

criterion = { default-features = false, git = "https://github.com/taiki-e/criterion.rs.git", rev = "fbc46df" } # https://github.com/bheisler/criterion.rs/pull/496 + patches to reduce deps more

[[bench]]
name = "parse"
path = "parse.rs"
harness = false
