name: Fuzz

permissions:
  contents: read

on:
  # Enable when running fuzzing on a branch.
  # push:
  #   branches:
  #     - fuzz
  schedule:
    - cron: '0 5,13,21 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings
  RUST_BACKTRACE: 1
  MAX_TOTAL_TIME: 2400 # 40 minutes

defaults:
  run:
    shell: bash

jobs:
  # TODO: Enable this once https://github.com/rust-fuzz/cargo-fuzz/issues/270 fixed.
  # # https://rust-fuzz.github.io/book/cargo-fuzz.html
  # # https://github.com/rust-fuzz/cargo-fuzz
  # # https://github.com/rust-fuzz/libfuzzer
  # libfuzzer:
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         persist-credentials: false
  #     - uses: taiki-e/github-actions/install-rust@main
  #     - run: cargo install cargo-fuzz
  #     - run: cargo fuzz run --fuzz-dir . parse -- -max_total_time="$MAX_TOTAL_TIME"
  #       working-directory: fuzz/libfuzzer

  # https://rust-fuzz.github.io/book/afl.html
  # https://github.com/rust-fuzz/afl.rs
  afl:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: taiki-e/github-actions/install-rust@main
      - run: cargo install afl
      - run: echo 'core' | sudo tee /proc/sys/kernel/core_pattern
      - run: cargo afl build && cargo afl fuzz -i in -o out -V "$MAX_TOTAL_TIME" target/debug/parse
        working-directory: fuzz/afl
